services:
  springboot-app:
    build: .
    container_name: backend-app
    depends_on:
      - db
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://fullstack_be_db:5432/fullstack-be
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: shoaib123
    networks:
      - fullstackbenetwork

  db:
    image: postgres:16
    container_name: fullstack_be_db
    environment:
      POSTGRES_DB: fullstack-be
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: shoaib123
    ports:
      - "5425:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - fullstackbenetwork

networks:
  fullstackbenetwork:
    driver: bridge